events {}
http {
    upstream backend {
        server 10.128.2.92:3000 weight=1;
        server 10.128.3.92:3000 weight=3;
        server 10.128.4.92:3000 backup;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}